before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
dockers:
  - image_templates:
    - "ghcr.io/cyb3r-jak3/example_http_server:latest"
    - "ghcr.io/cyb3r-jak3/example_http_server:{{ .Tag }}"
    - "ghcr.io/cyb3r-jak3/example_http_server:v{{ .Major }}"
    goarch: amd64
    dockerfile: release.Dockerfile
    use_buildx: true
    build_flag_templates:
    - "--platform=linux/amd64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"

  - image_templates:
    - "ghcr.io/cyb3r-jak3/example_http_server:latest-arm64"
    - "ghcr.io/cyb3r-jak3/example_http_server:{{ .Tag }}-arm64"
    - "ghcr.io/cyb3r-jak3/example_http_server:v{{ .Major }}-arm64"
    goarch: arm64
    dockerfile: release.Dockerfile
    use_buildx: true
    build_flag_templates:
    - "--platform=linux/arm64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
signs:
  - artifacts: all
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]