before:
  hooks:
    - go mod tidy -v
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
dockers:
  - 
    image_templates:
    - "ghcr.io/cyb3r-jak3/simple_http_server:latest"
    - "ghcr.io/cyb3r-jak3/simple_http_server:{{ .Tag }}"
    - "ghcr.io/cyb3r-jak3/simple_http_server:v{{ .Major }}"
    - "cyb3rjak3/simple_http_server:latest"
    - "cyb3rjak3/simple_http_server:{{ .Tag }}"
    - "cyb3rjak3/simple_http_server:v{{ .Major }}"
    goarch: amd64
    dockerfile: release.Dockerfile
    use_buildx: true
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.source=https://github.com/Cyb3r-Jak3/simple_http_server"

  - 
    image_templates:
    - "cyb3rjak3/simple_http_server:latest-arm64v8"
    - "cyb3rjak3/simple_http_server:{{ .Tag }}-arm64v8"
    - "cyb3rjak3/simple_http_server:v{{ .Major }}-arm64v8"
    - "ghcr.io/cyb3r-jak3/simple_http_server:latest-arm64v8"
    - "ghcr.io/cyb3r-jak3/simple_http_server:{{ .Tag }}-arm64v8"
    - "ghcr.io/cyb3r-jak3/simple_http_server:v{{ .Major }}-arm64v8"
    goarch: arm64
    dockerfile: release.Dockerfile
    use_buildx: true
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/Cyb3r-Jak3/simple_http_server"

docker_manifests:
# - name_template: ghcr.io/cyb3r-jak3/simple_http_server:{{ .Version }}
#   image_templates:
#   - ghcr.io/cyb3r-jak3/simple_http_server:{{ .Version }}-amd64
#   - ghcr.io/cyb3r-jak3/simple_http_server:{{ .Version }}-arm64v8
- name_template: cyb3r-jak3/simple_http_server:{{ .Version }}
  image_templates:
  - cyb3rjak3/simple_http_server:{{ .Version }}-amd64
  - cyb3rjak3/simple_http_server:{{ .Version }}-arm64v8

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
signs:
  - artifacts: all
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]