name: Publish Docker

on: [push]

jobs:
  Build_Push:
    runs-on: ubuntu-latest
    steps:
      - name: Login To GitHub
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - uses: actions/checkout@v2
      - name: Setup ENV
        run: |
          echo "BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`" >> $GITHUB_ENV
          echo "VCS_REF=`git rev-parse --short HEAD`" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2.1.5
        with:
          path: /tmp/.buildx-cache
          key: buildx-experimental-${{ github.sha }}
          restore-keys: buildx-experimental

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=h-action@v2
          push: ${{ env.branch == 'main' }}
          file: Dockerfile
          tags: ghcr.io/cyb3r-jak3/example_http_server:latest
          build-args: |
              BUILD_DATE=${BUILD_DATE}
              VCS_REF=${VCS_REF}
      
      - name: Inspect
        run: docker inspect ghcr.io/cyb3r-jak3/example_http_server:latest