name: Release Checking

on:
  pull_request:
    branches:
      - main


jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    -
      name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    -
      name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v4
      if: ${{ env.PASSPHRASE != '' }}
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
      env:
        PASSPHRASE: ${{ secrets.PASSPHRASE }}

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    -
      name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2.7.0
      if: ${{ env.GPG_FINGERPRINT != '' }}
      with:
        version: latest
        args: --snapshot --skip-publish --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}

    - name: dist artifacts
      uses: actions/upload-artifact@v2
      with:
        name: GoReleaser
        path: dist